#ifndef ROBOT_PARAMETERS_H_INCLUDED
#define ROBOT_PARAMETERS_H_INCLUDED

#define WHEEL_RADIUS				0.0975
#define DISTANCE_BETWEEN_WHEELS		0.3810
#define ROBOT_VELOCITY				0.10 
#define PI							3.14159265359
#define STEER_ANGLE					PI / 60.0

#endif // !ROBOT_PARAMETERS_H_INCLUDED
