#ifndef WINDOW_PARAMETERS_H_INCLUDED
#define WINDOW_PARAMETERS_H_INCLUDED

#define W_H					600
#define W_W					600
#define FPS					20
#define GRID_COLUMN_NUM		61
#define GRID_ROW_NUM		61

#endif // !WINDOW_PARAMETERS_H_INCLUDED
